version: '3'
services:
  api:
    image: backend
    build: 
      context: ./backend
    container_name: backend
    environment:
      MYSQL_HOST : mysql
      MYSQL_USER : root
      MYSQL_PASSWORD: phuocvnd
      MYSQL_DATABASE : todo
    ports:
      - '8001:8001'
    volumes:
      - /Users/admin/Desktop/WebServer/app/backend/data:/data
      - /Users/admin/Desktop/WebServer/app/backend/models_AI:/models_AI
    networks:
      - my-networks
    depends_on:
      - mysql
  db:
    image: database
    container_name: database_mysql
    restart: always
    ports:
      -0801:0801
    environment:
      MYSQL_ROOT_PASSWORD: phuocvnd
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: phuocvnd
      MYSQL_PASSWORD: phuocvnd
      networks:
        - my-network

networks:
  my_network:
    driver: bridge

