@hostname = localhost
@port = 8001
@host = {{hostname}}:{{port}}

### Successq
POST http://{{host}}/prediction HTTP/1.1
content-type: application/json

{
    "array": [152. ,  14. ]
}

### Successq
POST http://{{host}}/items HTTP/1.1
content-type: application/json

{
    "name": "Phuoc",
    "description": "ssfsd",
    "price": 5,
    "tax": 6
}

### Successq
POST http://{{host}}/prediction HTTP/1.1
content-type: application/json

{
    "flow" : 112,
    "pressure": 15.5

}

### Success
GET  http://{{host}}/prediction/130/14 HTTP/1.1
content-type: application/json

{

}


### Success
GET  http://{{host}}/items/ HTTP/1.1
content-type: application/json

{

}